name: Contexts
on: push
jobs:
  contexts:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      NAME: ${{ vars.Name }}
      REPO_ID: ${{ github.repository_id }}
    steps:
      - run: echo "${{ github.actor  }}"
      - run: echo "${{ github.run_id }}"
      - run: echo "${{ github.server_url }}"
      - run: echo "${{ github.repository_owner }}"
      - run: echo "${{ github.repositoryUrl }}"
      - run: echo "${{ runner.name  }}"
      - run: echo "${{ runner.os }}"
      - run: echo "${BRANCH}"
      - run: echo "${NAME}"
      - run: echo "${REPO_ID}"
