name: Hello
on: 
  # 手動実行イベント
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: Alice
        required: true
        description: Your name here.
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.name }}."
      - uses: actions/checkout@v4
  bye:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye"
      - uses: actions/checkout@v4
